#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define GPIO_0_DEFAULT_MAP {GPIO_0,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_1_DEFAULT_MAP {GPIO_1,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},

/* gpio_id, second_func_en, second_func_dev, time_sharing_func_dev, pull_mode, int_en, int_type, low_power_io_ctrl, driver_capacity, gpio_skip */
#define GPIO_DEFAULT_DEV_CONFIG  \
{\
    GPIO_0_DEFAULT_MAP \
    GPIO_1_DEFAULT_MAP \
    /* SCH-7259 V1.0: P2/P3 are BK3515NS UART1 flow control, not SDIO0. */\
    {GPIO_2,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_3,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_INPUT,      GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    /* P4_GPS_EN; keep GPS disabled until its owner explicitly enables it. */\
    {GPIO_4,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_5,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_6,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_ENABLE,  GPIO_INT_TYPE_FALLING_EDGE, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_7,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_8,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_9,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_I2S0_DOUT,       GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_12, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_DOWN_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    /* P13_MUTE on the new board; it is no longer an SD-card LDO control. */\
    {GPIO_13, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    /* SCH-7259 V1.0 SD-NAND: SDIO1, 4-bit bus on P14-P19. */\
    {GPIO_14, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO1_HOST_CLK,   GPIO_DEV_INVALID,   GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_15, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO1_HOST_CMD,   GPIO_DEV_INVALID,   GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_16, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO1_HOST_DATA0, GPIO_DEV_INVALID,   GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_17, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO1_HOST_DATA1, GPIO_DEV_INVALID,   GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_18, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO1_HOST_DATA2, GPIO_DEV_INVALID,   GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_19, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO1_HOST_DATA3, GPIO_DEV_INVALID,   GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_20, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R6,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_21, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R5,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_22, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R4,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_23, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R3,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_24, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G7,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_25, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G6,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_26, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G5,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_27, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_MCLK,       GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_28, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2S0_MCLK,       GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_29, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PCLK,       GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_30, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_HSYNC,      GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_31, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_VSYNC,      GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_32, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA0,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_33, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA1,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_34, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA2,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_35, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA3,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_36, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA4,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_37, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA5,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_38, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA6,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    /* P39_3V3-E_EN: 3V3-E feeds SD_VDD through R61; drive high at boot. */\
    {GPIO_39, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    /* P40_TP_RST / P41_TP_INT — SCH-7259 V1.0 TP control.
     * INT needs INPUT (runtime IRQ) + OUTPUT (GT911 addr select at reset). */\
    {GPIO_40, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_41, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_INPUT,      GPIO_DEV_GPIO_OUTPUT,GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    /* MIPI LCD reset (P42_LCD_RST). */\
    {GPIO_42, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    /* P43_IIC1_SDA / P44_IIC1_CLK — SCH-7259 V1.0 TP software I2C (OD inout). */\
    {GPIO_43, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_44, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    /* LCD panel control/power enable (P45_LCD_PCTRL); driven high before panel init. */\
    {GPIO_45, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    /* LCD backlight (P46_LCD_BL); driven high before panel init. */\
    {GPIO_46, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    {GPIO_47, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B3,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    {GPIO_48, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R2,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    {GPIO_49, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R1,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    {GPIO_50, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R0,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    {GPIO_51, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G1,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    {GPIO_52, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G0,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    {GPIO_53, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B2,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    {GPIO_54, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B1,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    {GPIO_55, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B0,          GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    {GPIO_59, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_CLK_AUXS_CIS,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_60, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_64, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_UART5_RXD,       GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_65, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_UART5_TXD,       GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_69, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_70, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_71, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
}

#ifdef __cplusplus
}
#endif
