#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define GPIO_0_DEFAULT_MAP  {GPIO_0,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_UART1_RXD,   GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},
#define GPIO_1_DEFAULT_MAP  {GPIO_1,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_UART1_TXD,   GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},
#define GPIO_2_DEFAULT_MAP  {GPIO_2,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT, GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},
#define GPIO_3_DEFAULT_MAP  {GPIO_3,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_INPUT,  GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},
#define GPIO_4_DEFAULT_MAP  {GPIO_4,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT, GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},
#define GPIO_5_DEFAULT_MAP  {GPIO_5,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,     GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},
#define GPIO_6_DEFAULT_MAP  {GPIO_6,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,     GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},
#define GPIO_40_DEFAULT_MAP {GPIO_40, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT, GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_41_DEFAULT_MAP {GPIO_41, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_INPUT,  GPIO_DEV_GPIO_OUTPUT,GPIO_PULL_UP_EN,   GPIO_INT_ENABLE,  GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_43_DEFAULT_MAP {GPIO_43, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT, GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_44_DEFAULT_MAP {GPIO_44, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT, GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_14_DEFAULT_MAP {GPIO_14, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO1_HOST_CLK,   GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_15_DEFAULT_MAP {GPIO_15, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO1_HOST_CMD,   GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_16_DEFAULT_MAP {GPIO_16, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO1_HOST_DATA0, GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_17_DEFAULT_MAP {GPIO_17, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO1_HOST_DATA1, GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_18_DEFAULT_MAP {GPIO_18, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO1_HOST_DATA2, GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_19_DEFAULT_MAP {GPIO_19, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO1_HOST_DATA3, GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_38_DEFAULT_MAP {GPIO_38, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA6, GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},
#define GPIO_39_DEFAULT_MAP {GPIO_39, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_GPIO_OUTPUT, GPIO_DEV_INVALID, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},

/* gpio_id, second_func_en, second_func_dev, time_sharing_func_dev, pull_mode, int_en, int_type, low_power_io_ctrl, driver_capacity, gpio_skip */
#define GPIO_DEFAULT_DEV_CONFIG  \
{\
    GPIO_0_DEFAULT_MAP \
    GPIO_1_DEFAULT_MAP \
    GPIO_2_DEFAULT_MAP \
    GPIO_3_DEFAULT_MAP \
    GPIO_4_DEFAULT_MAP \
    GPIO_5_DEFAULT_MAP \
    GPIO_6_DEFAULT_MAP \
    {GPIO_7,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_8,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_9,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_I2S0_DOUT,       GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_12, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_DOWN_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    /* P13_MUTE on the new board; it is no longer an SD-card LDO control. */\
    {GPIO_13, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    GPIO_14_DEFAULT_MAP \
    GPIO_15_DEFAULT_MAP \
    GPIO_16_DEFAULT_MAP \
    GPIO_17_DEFAULT_MAP \
    GPIO_18_DEFAULT_MAP \
    GPIO_19_DEFAULT_MAP \
    /* MIPI DSI uses dedicated pads. Remove stale RGB mappings from the new board's SWD/CAN pins. */\
    {GPIO_20, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SWCLK,           GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_21, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SWDIO,           GPIO_DEV_CAN_STANDBY,GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_22, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_CAN_TX,     GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_23, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_CAN_RX,     GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_24, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_25, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_26, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    /* V1.0 board keys: P27 down / P30 middle / P32 up / P31 left / P29 right (active low). */\
    {GPIO_27, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_INPUT,      GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_28, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_29, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_INPUT,      GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_30, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_INPUT,      GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_31, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_INPUT,      GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_32, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_INPUT,      GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_33, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA1,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_34, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA2,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_35, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA3,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_36, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA4,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_37, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA5,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    GPIO_38_DEFAULT_MAP \
    GPIO_39_DEFAULT_MAP \
    GPIO_40_DEFAULT_MAP \
    GPIO_41_DEFAULT_MAP \
    /* MIPI LCD reset (P42_LCD_RST). */\
    {GPIO_42, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    GPIO_43_DEFAULT_MAP \
    GPIO_44_DEFAULT_MAP \
    /* LCD panel control/power enable (P45_LCD_PCTRL); driven high before panel init. */\
    {GPIO_45, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    /* LCD backlight (P46_LCD_BL); driven high before panel init. */\
    {GPIO_46, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
    /* P47-P55 are NFC/UART4/CAT.1 signals on SCH-7259, not parallel LCD data. */\
    {GPIO_47, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_48, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_49, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_50, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_51, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_52, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_53, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_54, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_55, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_59, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_CLK_AUXS_CIS,    GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_60, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_64, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_UART5_RXD,       GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_65, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_UART5_TXD,       GPIO_DEV_INVALID,    GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_69, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
    {GPIO_70, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_GPIO_OUTPUT,      GPIO_DEV_INVALID, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
    {GPIO_71, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
}

#ifdef __cplusplus
}
#endif
